services:
  local_roach:
    image: cockroachdb/cockroach:latest
    container_name: local_roach
    ports:
      - "8080:8080"  # Cockroach console
      - "26257:26257"  # DB
    volumes:
      - ./local_roach:/cockroach/cockroach-data
    command:
      - start-single-node
      - --insecure
    networks:
      - portfolio_site_network
  local_db:
    build:
      context: ./backend/db
      dockerfile: ./db.Dockerfile
    image: local_db
    container_name: local_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db/modules:/app/modules  # Allows for hot reload
    networks:
      - portfolio_site_network
    environment:
      - API_HOST=localhost
      - DATABASE_URL=cockroachdb://root@local_roach:26257/defaultdb
    depends_on:
      - local_roach
  local_api:
    build:
      context: ./backend/api
      dockerfile: ./api.Dockerfile
    image: local_api
    container_name: local_api
    ports:
      - "4000:4000"
    networks:
      - portfolio_site_network
    environment:
      - DB_HOST=http://local_db:8000
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - IAP_AUDIENCE_ID=885358676606-0nn6c23i8m1nu8j831urkaq314e1up5e.apps.googleusercontent.com
    depends_on:
      - local_db
      - local_email
  local_email:
    build:
      context: ./backend/email
      dockerfile: ./email.Dockerfile
    image: local_email
    container_name: local_email
    ports:
      - "5000:5000"
    volumes:
      - ~/.config/gcloud:/.config/gcloud  # Use gcloud application default credentials
    networks:
      - portfolio_site_network
  local_frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.Dockerfile
    image: local_frontend
    container_name: local_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src  # Allows for hot reload
    networks:
      - portfolio_site_network
    environment:
      - API_HOST=http://local_api:4000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/src/lib/service-account.json
      - IAP_AUDIENCE_ID=885358676606-0nn6c23i8m1nu8j831urkaq314e1up5e.apps.googleusercontent.com



networks:
  portfolio_site_network:
    driver: bridge
    name: portfolio_site_network
